name: medical_chatbot
channels:
  # - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy
  - joblib
  - pandas
  - nltk
  - pip
  - collections
  - pip:
    - PyQt5==5.15.10
    - scikit-learn==1.3.0
    - gensim
    - PyQtWebEngine
    - spellwise
    - openai
    - python-dotenv
  - ipykernel
