name: medical_chatbot
channels:
  # - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy
  - joblib
  - pandas
  - nltk
  - pip
  - pip:
    - PyQt5
    - scikit-learn=1.3.0
    - gensim
  - ipykernel
